version: "3"

services:
  serverless_node_api:
    image: amaysim/serverless:2.68.0
    container_name: serverless_node_api
    network_mode: host
    volumes:
      - ./:/app
    working_dir: /app/api
    env_file: .env
  serverless_node_front:
    image: amaysim/serverless:2.68.0
    container_name: serverless_node_front
    network_mode: host
    volumes:
      - ./:/app
    working_dir: /app/front
    env_file: .env
